Adapt to new sdk
eclipse-velocitas/vehicle-app-cpp-template pull request #12
Opened 2022-11-30 13:08 UTC by doosuu

# Description

Update the template to the latest changes in the SDK.

## Azure DevOps PBI/Task reference

AB#_[PBI/Task number]_

## Checklist

* [ ] Vehicle App can be started with dapr run and is connecting to vehicle data broker
* [ ] Vehicle App can process MQTT messages and call the seat service
* [ ] Vehicle App can be deployed to local K3D and is running
* [ ] Created/updated tests, if necessary. Code Coverage percentage on new code shall be >= 70%.
* [ ] Extended the documentation in Velocitas repo
* [ ] Extended the documentation in README.md

* [ ] Devcontainer can be opened successfully
* [ ] Devcontainer can be opened successfully behind a corporate proxy
* [ ] Devcontainer can be re-built successfully

* [ ] Release workflow is passing

2022-12-01 12:10 UTC, MP91 requested changes

2022-12-01 12:10 UTC, MP91 commented on app/src/Launcher.cpp
>  #include <fmt/core.h>
import can be removed -> please check where we can remove the import

2022-12-20 05:36 UTC, doosuu commented on app/src/Launcher.cpp
>  #include <fmt/core.h>
Removed this include, others cannot be removed in template.

2022-12-20 08:43 UTC, dennismeister93 approved these changes
lgtm

2022-12-20 08:51 UTC, closed without merging