Update/bi sec
eclipse-velocitas/vehicle-app-cpp-template pull request #54
Opened 2023-06-23 09:13 UTC by kse3hi

# Description

Update packages:
* devenv-github-workflows@v2.0.9
* devenv-devcontainer-setup@v1.1.9
* devcontainer-base-image@v1.0.3
* cpp-sdk@v0.3.2

Fix CVE-2022-4904

## Issue ticket number and link

ADO#15373

## Checklist

* [ ] Vehicle App can be started with dapr run and is connecting to vehicle data broker
* [ ] Vehicle App can process MQTT messages and call the seat service
* [ ] Vehicle App can be deployed to local K3D and is running
* [ ] Created/updated tests, if necessary. Code Coverage percentage on new code shall be >= 70%.
* [ ] Extended the documentation in Velocitas repo
* [ ] Extended the documentation in README.md

* [ ] Devcontainer can be opened successfully
* [ ] Devcontainer can be opened successfully behind a corporate proxy
* [ ] Devcontainer can be re-built successfully

* [ ] Release workflow is passing

2023-06-23 12:18 UTC, BjoernAtBosch requested changes

2023-06-23 12:18 UTC, BjoernAtBosch commented on sdk
Please update to moved label ...

2023-06-26 06:09 UTC, kse3hi commented on sdk
Sorry, forgot to push the latest changes :)

2023-06-26 07:29 UTC, BjoernAtBosch commented on sdk
No problem

2023-06-26 07:29 UTC, BjoernAtBosch approved these changes
LGTM

2023-06-26 08:53 UTC, merged