feature: Adapt to manifest v3
eclipse-velocitas/vehicle-app-cpp-template pull request #63
Opened 2023-08-21 13:23 UTC by doosuu

# Description

This PR adapts the template to use the new app manifest v3 structure.

## Issue ticket number and link

## Checklist

* [ ] Vehicle App can be started with dapr run and is connecting to vehicle data broker
* [ ] Vehicle App can process MQTT messages and call the seat service
* [ ] Vehicle App can be deployed to local K3D and is running
* [ ] Created/updated tests, if necessary. Code Coverage percentage on new code shall be >= 70%.
* [ ] Extended the documentation in Velocitas repo
* [ ] Extended the documentation in README.md

* [ ] Devcontainer can be opened successfully
* [ ] Devcontainer can be opened successfully behind a corporate proxy
* [ ] Devcontainer can be re-built successfully

* [ ] Release workflow is passing

2023-08-24 13:33 UTC, BjoernAtBosch requested changes
One question and some proposed fixes

2023-08-24 13:33 UTC, BjoernAtBosch commented on .github/workflows/build-docker-image.yml
> -        value: ${{ jobs.build-image.outputs.digest }}
Why removing this? Not needed any more?

2023-08-24 13:33 UTC, BjoernAtBosch commented on app/AppManifest.json
> +                            "access": "write"
Actually not used - remove:
```suggestion
```

2023-08-24 13:33 UTC, BjoernAtBosch commented on app/src/SampleApp.cpp
> +                 velocitas::IPubSubClient::createInstance("SeatAdjusterApp")) {}
```suggestion
                 velocitas::IPubSubClient::createInstance("SampleApp")) {}
```

2023-08-24 13:33 UTC, BjoernAtBosch commented on app/src/SampleApp.cpp
> +const auto DATABROKER_SUBSCRIPTION_TOPIC = "seatadjuster/currentPosition";
```suggestion
const auto GET_SPEED_REQUEST_TOPIC       = "sampleapp/getSpeed";
const auto GET_SPEED_RESPONSE_TOPIC      = sampleapp/getSpeed/response";
const auto DATABROKER_SUBSCRIPTION_TOPIC = "sampleapp/currentSpeed";
```

2023-08-24 13:33 UTC, BjoernAtBosch commented on app/AppManifest.json
> +                    "seatadjuster/currentPosition"
```suggestion
                "reads": [ "sampleapp/getSpeed" ],
                "writes": [
                    "sampleapp/getSpeed/response",
                    "sampleapp/currentSpeed"
```

2023-08-24 17:21 UTC, doosuu commented on .github/workflows/build-docker-image.yml
> -        value: ${{ jobs.build-image.outputs.digest }}
@MP91 can you elaborate why this was removed?

2023-08-25 04:34 UTC, MP91 commented on .github/workflows/build-docker-image.yml
> -        value: ${{ jobs.build-image.outputs.digest }}
Because I did not saw any place where it is used. Did I miss something?

2023-08-25 07:54 UTC, doosuu commented on .github/workflows/build-docker-image.yml
> -        value: ${{ jobs.build-image.outputs.digest }}
Looks good from my side, the output variables were never used, where they @MP91 ?

2023-08-25 08:04 UTC, BjoernAtBosch approved these changes
LGTM

2023-08-25 08:07 UTC, MP91 commented on .github/workflows/build-docker-image.yml
> -        value: ${{ jobs.build-image.outputs.digest }}
I thought we were talking just about that :D But no I did not find any place were we used it...

2023-08-25 08:57 UTC, merged